CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(4000) NOT NULL,
    price NUMERIC(12, 2) NOT NULL CHECK (price > 0),
    image_url VARCHAR(2048) NOT NULL,
    category_id BIGINT NOT NULL REFERENCES category(id),
    active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX idx_equipment_category ON equipment(category_id);

-- The row exists even before import, providing a lock shared by all application instances.
CREATE TABLE catalog_import (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    completed_at TIMESTAMP WITH TIME ZONE,
    imported_count INTEGER
);
INSERT INTO catalog_import(id) VALUES (1);
